### ISSUE TITLE
Delete this?!

### ISSUE THREAD

**Issue by amouat** [ksanjeev/Astrology#1]
Found this by accident - seems to be highly sensitive information, I strongly suggest you contact Github to completely delete and purge this project.

**Comment by ksanjeev** [comment]
What is the issue?

**Comment by amouat** [comment]
You're happy with the general public being able to see and read all this stuff? Aren't you worried about identity theft etc?

I figured you thought this repo was private and hadn't realised you'd shared all this. It's totally up to you though, I'll close the issue.
